export const SET_TOKEN_NAME = "SET_TOKEN_NAME";
export const SET_TOKEN_SYMBOL = "SET_TOKEN_SYMBOL";
export const SET_DECIMALS = "SET_DECIMALS";
export const SET_TOKEN_OWNER = "SET_TOKEN_OWNER";
export const SET_TOKEN_TYPE = "SET_TOKEN_TYPE";
export const SET_TOTAL_SUPPLY = "SET_TOTAL_SUPPLY";
export const SET_ACCOUNTS = "SET_ACCOUNTS";
export const SET_LOADING_ACCOUNTS = "SET_LOADING_ACCOUNTS";
export const SET_APP_STATE = "SET_APP_STATE";
export const SET_CHECKING_TOKEN_OWNER_FUNDS = "SET_CHECKING_TOKEN_OWNER_FUNDS";
export const SET_TOKEN_OWNER_HAS_ENOUGH_FUNDS = "SET_TOKEN_OWNER_HAS_ENOUGH_FUNDS";
export const SET_INFO_MESSAGE = "SET_INFO_MESSAGE";




