export const SET_TOKEN_NAME = "SET_TOKEN_NAME";
export const SET_TOKEN_SYMBOL = "SET_TOKEN_SYMBOL";
export const SET_DECIMALS = "SET_DECIMALS";
export const SET_TOKEN_OWNER = "SET_TOKEN_OWNER";
export const SET_TOKEN_TYPE = "SET_TOKEN_TYPE";

